apiVersion: v1
kind: Pod
metadata:
  name: mypod 
  labels:
    run: mypod
spec:
  containers:
  - image: australia-southeast2-docker.pkg.dev/sit737-25t1-dona-3ac918c/calculator/cal:1 
    name: nodewebapp
    ports:
    - containerPort: 3041 
  dnsPolicy: ClusterFirst
  rescartrolicy: Always