apiVersion: v1
kind: Pod
metadata:
  name: mypod 
  labels:
    run: mypod
spec:
  containers:
  - image: kaushi11/calculator:1
    name: nodewebapp
    ports:
    - containerPort: 3041 
  dnsPolicy: ClusterFirst
  restartPolicy: Always