apiVersion: v1
kind: Service
metadata:
  name: text-toolkit-service
spec:
  type: LoadBalancer
  selector:
    app: text-toolkit
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3041

---

apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017