name: Delete Kubernetes Resources

on:
  push:
    branches:
      - sit737-2025-prac8hd 

jobs:
  delete:
    name: Delete Kubernetes Resources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Authenticate to GCP
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > "${HOME}/gcloud-key.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcloud-key.json"


      - name: Install gke-gcloud-auth-plugin and get credentials
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GCP_REGION }}

      - name: Delete Kubernetes resources
        run: |
          kubectl delete -f k8s/createDeployment.yaml --ignore-not-found
          kubectl delete -f k8s/createService.yaml --ignore-not-found
          kubectl delete -f k8s/createPersistentVolumeClaim.yaml --ignore-not-found
          kubectl delete -f k8s/mongo-backup-job.yaml --ignore-not-found
